/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-29 16:47:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Updatecustomerform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  background: url(\"https://s3-us-west-2.amazonaws.com/s.cdpn.io/38816/image-from-rawpixel-id-2210775-jpeg.jpg\") center center no-repeat;\r\n");
      out.write("  background-size: cover;\r\n");
      out.write("  width: 100vw;\r\n");
      out.write("  height: 100vh;\r\n");
      out.write("  display: grid;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".contact-us {\r\n");
      out.write("  background: #f8f4e5;\r\n");
      out.write("  padding: 50px 100px;\r\n");
      out.write("  border: 2px solid black;\r\n");
      out.write("  box-shadow: 15px 15px 1px #ffa580, 15px 15px 1px 2px black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  font-size: 14pt;\r\n");
      out.write("  line-height: 28pt;\r\n");
      out.write("  font-family: \"Fjalla One\";\r\n");
      out.write("  margin-bottom: 28pt;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-bottom: 5px solid black;\r\n");
      out.write("  background: #f8f4e5;\r\n");
      out.write("  min-width: 250px;\r\n");
      out.write("  padding-left: 5px;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus {\r\n");
      out.write("  border-bottom: 5px solid #ffa580;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" button {\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  line-height: 28pt;\r\n");
      out.write("  padding: 0 20px;\r\n");
      out.write("  background: #ffa580;\r\n");
      out.write("  letter-spacing: 2px;\r\n");
      out.write("  transition: 0.2s all ease-in-out;\r\n");
      out.write("  outline: none;\r\n");
      out.write("  border: 1px solid black;\r\n");
      out.write("  box-shadow: 3px 3px 1px 1px #95a4ff, 3px 3px 1px 2px black;\r\n");
      out.write("}\r\n");
      out.write("button:hover {\r\n");
      out.write("  background: black;\r\n");
      out.write("  color: white;\r\n");
      out.write("  border: 1px solid black;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("::selection {\r\n");
      out.write("  background: #ffc8ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:-webkit-autofill,\r\n");
      out.write("input:-webkit-autofill:hover,\r\n");
      out.write("input:-webkit-autofill:focus {\r\n");
      out.write("  border-bottom: 5px solid #95a4ff;\r\n");
      out.write("  -webkit-text-fill-color: #2A293E;\r\n");
      out.write("  -webkit-box-shadow: 0 0 0px 1000px #f8f4e5 inset;\r\n");
      out.write("  transition: background-color 5000s ease-in-out 0s;\r\n");
      out.write("}</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"contact-us\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "customerindex.jsp", out, false);
      out.write("\r\n");
      out.write("<p> Update form</p>\r\n");
      out.write("<form action=\"Updatecustomer.jsp\"><br>\r\n");
      out.write(" <input type=\"number\" placeholder=\"enter CId\"  name=\"cid\" />\r\n");
      out.write(" <input type=\"number\" placeholder=\"mobile number to update \"  name=\"mobno\" />\r\n");
      out.write("\r\n");
      out.write(" <input type=\"submit\"/> \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
